
.PHONY: build test_suite install evaluation clean mrproper all

all: build

CoqMakefile: _CoqProject
	@echo "Generating $@ from $<."
	@coq_makefile -o $@ -f $<


CoqMakefileTests: _CoqProjectTests
	@echo "Generating $@ from $<."
	@coq_makefile -o $@ -f $<


build: CoqMakefile
	@echo "Compiling Rocq code."
	@$(MAKE) -f CoqMakefile all

test_suite: build CoqMakefileTests
	@echo "Starting test suite."
	@$(MAKE) -f CoqMakefileTests all

install: build
	@echo "Installing."
	@$(MAKE) -f CoqMakefile install

evaluation: build
	@echo "Starting evaluation"
	@bash ./evaluation.sh

# The "clean" target (first) cleans up the intermediate files from the
# Rocq formalisation.
clean:
	@echo "Cleaning up intermediate files generated by Rocq."
	@$(MAKE) -f CoqMakefile clean
	@rm -rf **/*.{vo,vok,vos,glob} **/.*.aux
	@rm -rf ./evaluation_out/


# The "mrproper" target (first) does a "clean" and additionally removes
# the CoqMakefile and all byproducts of "coq_makefile"
mrproper: clean
	@echo "Cleaning up the rest of intermediate files generated by Rocq."
	@$(MAKE) -f CoqMakefile cleanall
	@$(MAKE) -f CoqMakefileTests cleanall
	@echo "Deleting CoqMakefile."
	@rm -f CoqMakefile*
